fix handling of request exceptions in client.js (#196)
When a network or internal exception is thrown when making the http request
via needle (for example when mocking via unit tests using "nock"), it would
throw a TypeError in Client.handleErrors() because reason.options was not set
for those error (reason is the caught error object):

    TypeError: Cannot read property 'method' of undefined

This fixes it by adding the necessary structure upon errors inside rp().